### ISSUE TITLE
执行npm start 就报错， Cannot find module '/root/UAT/UI/src/pages/User/Login'

### ISSUE THREAD

**Issue by rofleed** [t880216t/UAT#1]
报错信息如下：

npm start

> ant-design-pro@1.0.0 start /root/UAT/UI
> umi dev

🚀 Starting Umi UI using umi@2.13.13...
⛽️ Ready on http://localhost:3000/
Plugin apply failed: Cannot find module '/root/UAT/UI/src/pages/User/Login'
/root/UAT/UI/node_modules/umi-build-dev/lib/Service.js:314
        throw e;
        ^

Error: Cannot find module '/root/UAT/UI/src/pages/User/Login'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at routes.reduce (/root/UAT/UI/node_modules/umi-build-dev/lib/Service.js:378:98)
    at Array.reduce (<anonymous>)
    at getComponents (/root/UAT/UI/node_modules/umi-build-dev/lib/Service.js:376:21)
    at routes.reduce (/root/UAT/UI/node_modules/umi-build-dev/lib/Service.js:383:30)
    at Array.reduce (<anonymous>)
    at getComponents (/root/UAT/UI/node_modules/umi-build-dev/lib/Service.js:376:21)
    at Service.getRouteComponents (/root/UAT/UI/node_modules/umi-build-dev/lib/Service.js:390:32)
    at Array.api.modifyAFWebpackOpts.memo (/root/UAT/UI/node_modules/umi-build-dev/lib/plugins/commands/block/ui/index.js:32:27)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ant-design-pro@1.0.0 start: `umi dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ant-design-pro@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-28T07_16_04_030Z-debug.log

**Comment by t880216t** [comment]
这个看样子是特定系统下识别文件的问题，试着把‘/UAT/UI/src/pages/User/login.js’改成大写的Login.js试试
